server:
  port: 8080



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: milan123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet